# Base configs
#baseurl: "https://photography.rampatra.com"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Abdelmouttaleb Dakri"
subtitle: "Hidden in the bowels of an inaccessible website, behold my bland still pictures!"
author: "Abdelmouttaleb Dakri by way of Ram Patra"
header:
 title: "Photography"
 subtitle: "by Abdelmouttaleb Dakri"
footer:
 name: "Hey there, my name is Abdelmouttaleb (a.k.a Abdel)"
 bio: "These are pictures that I took with a Nikon D3200 with a 18-55 mm objective, the plainest set-up in the world for proabably just me to enjoy ;)"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://www.twitter.com/dakriabdo"
  instagram: "https://www.instagram.com/anewbie_adakri"
  linkedin: "https://in.linkedin.com/in/abdelmouttaleb-dakri"
  github: "https://www.github.com/adakri"
